Repository autobrr/mkbrr, pull requests merged in 2025-02, with the labels that each got.

#9 fix(root): silence help text after error
  cmd/root.go
Labels: cli

#11 feat(cmd): add self-update command
  .gitignore
  .goreleaser.yml
  README.md
  cmd/update.go
  go.mod
  go.sum
Labels: enhancement

#12 feat(cmd): add modify command
  README.md
  cmd/create.go
  cmd/modify.go
  cmd/root.go
  internal/preset/preset.go
  internal/torrent/create.go
  internal/torrent/display.go
  internal/torrent/modify.go
  internal/torrent/preset.go
  internal/torrent/types.go
Labels: enhancement

#17 feat(torrent): add limits per tracker
  .gitignore
  README.md
  cmd/create.go
  examples/presets.yaml
  internal/torrent/batch_test.go
  internal/torrent/create.go
  internal/torrent/create_test.go
  internal/torrent/display.go
  internal/torrent/hasher_test.go
  internal/trackers/trackers.go
  internal/trackers/trackers_test.go
  schema/presets.json
Labels: enhancement

#20 perf(torrent): optimize piece hashing and buffer management
  cmd/create.go
  internal/torrent/create.go
  internal/torrent/hasher.go
Labels: optimization

#24 fix(create): add option to omit creator string
  README.md
  cmd/create.go
Labels: bug, cli
